#OneHotEncoding From Scratch

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
tips=sns.load_dataset('tips')

In [3]:
tips.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

#return the unique categories from the data.

In [4]:
np.unique(tips['day'])

array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object)

#First of all  lets transform the categorical data to numeric using one hot encoding.

In [5]:
class OneHotEncoder:
    def __init__(self):
        pass

    def fit(self, column_array):
        self.categories_=np.unique(column_array)

    def transform(self,column_array):
        result=[]
        for value in column_array:
            row=[]
            for element in self.categories_:
                if value==element:
                    row.append(1)
                else:
                    row.append(0)
            result.append(row)
        return np.array(result)
    
    def fit_transform(self, column_array):
        self.fit(column_array)
        return self.transform(column_array)

In [6]:
onehot1=OneHotEncoder()
onehot2=OneHotEncoder()
onehot3=OneHotEncoder()
onehot4=OneHotEncoder()

In [7]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [8]:
encoded_sex=onehot1.fit_transform(tips['sex'])
encoded_smoker=onehot2.fit_transform(tips['smoker'])
encoded_day=onehot3.fit_transform(tips['day'])
encoded_time=onehot4.fit_transform(tips['time'])

#lets see the example of encoded day

In [9]:
encoded_day

array([[0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [10]:
print(onehot1.categories_)
print(onehot2.categories_)
print(onehot3.categories_)
print(onehot4.categories_)

['Female' 'Male']
['No' 'Yes']
['Fri' 'Sat' 'Sun' 'Thur']
['Dinner' 'Lunch']

#concatating the encoded values to original array

In [11]:
encoded=np.hstack((tips.values, encoded_sex, encoded_smoker,encoded_day, encoded_time))
encoded

array([[16.99, 1.01, 'Female', ..., 0, 1, 0],
       [10.34, 1.66, 'Male', ..., 0, 1, 0],
       [21.01, 3.5, 'Male', ..., 0, 1, 0],
       ...,
       [22.67, 2.0, 'Male', ..., 0, 1, 0],
       [17.82, 1.75, 'Male', ..., 0, 1, 0],
       [18.78, 3.0, 'Female', ..., 1, 1, 0]],
      shape=(244, 17), dtype=object)

#removing the encoded categorical datas

In [12]:
encoded=np.delete(encoded, np.s_[2:6], axis=1)
encoded

array([[16.99, 1.01, 2, ..., 0, 1, 0],
       [10.34, 1.66, 3, ..., 0, 1, 0],
       [21.01, 3.5, 3, ..., 0, 1, 0],
       ...,
       [22.67, 2.0, 2, ..., 0, 1, 0],
       [17.82, 1.75, 2, ..., 0, 1, 0],
       [18.78, 3.0, 2, ..., 1, 1, 0]], shape=(244, 13), dtype=object)

In [13]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [14]:
print(onehot1.categories_)
print(onehot2.categories_)
print(onehot3.categories_)
print(onehot4.categories_)

['Female' 'Male']
['No' 'Yes']
['Fri' 'Sat' 'Sun' 'Thur']
['Dinner' 'Lunch']

#Changing the numpy array into Dataframe for visualization

In [15]:
tips_encoded_columns=['total_bill', 'tip', 'Size', 'Sex_Female','Sex_Male', 'Smoker_No', 'Smoker_Yes', 'Day_Fri','Day_Sat','Day_Sun','Day_Thur', 'Time_Dinner', 'Time_Lunch']
encoded_tips=pd.DataFrame(encoded,columns=tips_encoded_columns)
encoded_tips.sample(10)

,total_bill,tip,Size,Sex_Female,Sex_Male,Smoker_No,Smoker_Yes,Day_Fri,Day_Sat,Day_Sun,Day_Thur,Time_Dinner,Time_Lunch
207,38.73,3.0,4,0,1,0,1,0,1,0,0,1,0
175,32.9,3.11,2,0,1,0,1,0,0,1,0,1,0
174,16.82,4.0,2,0,1,0,1,0,0,1,0,1,0
206,26.59,3.41,3,0,1,0,1,0,1,0,0,1,0
73,25.28,5.0,2,1,0,0,1,0,1,0,0,1,0
61,13.81,2.0,2,0,1,0,1,0,1,0,0,1,0
234,15.53,3.0,2,0,1,0,1,0,1,0,0,1,0
163,13.81,2.0,2,0,1,1,0,0,0,1,0,1,0
53,9.94,1.56,2,0,1,1,0,0,0,1,0,1,0
129,22.82,2.18,3,0,1,1,0,0,0,0,1,0,1